muster:
  muster:
    oauth:
      server:
        enabled: false
        storage:
          type: memory
  gatewayAPI:
    httpRoute:
      parentRefs:
        - name: giantswarm-default
          namespace: envoy-gateway-system
          group: gateway.networking.k8s.io
          kind: Gateway
      hostnames:
        - muster.ci.example.com

valkey:
  enabled: false
