{{- if .Values.dnsEndpoint.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{ include "name" . }}-dns
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    giantswarm.io/external-dns: managed
spec:
  endpoints:
    {{- range .Values.dnsEndpoint.hostnames }}
    - dnsName: {{ . }}
      recordTTL: {{ $.Values.dnsEndpoint.ttl }}
      recordType: {{ $.Values.dnsEndpoint.recordType }}
      targets:
        {{- range $.Values.dnsEndpoint.targets }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
{{- end }}
