{{- if (include "agentic-platform.ingress.agentgateway" .) }}
{{- $fullName := .Values.gateway.name }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
    {{- with (include "agentic-platform.httpRouteLabels" (dict "ctx" . "route" "mcp")) }}
    {{- . | nindent 4 }}
    {{- end }}
  {{- with (include "agentic-platform.httpRouteAnnotations" (dict "ctx" . "route" "mcp")) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.ingress.parentRefs | nindent 4 }}
  {{- with .Values.ingress.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp
      backendRefs:
        - name: {{ $fullName }}
          port: 8080
{{- end }}
